### ISSUE TITLE
Decidir como vamos a internacinoalizar este paquete

### ISSUE THREAD

**Issue by FvD** [ixpantia/ixplorer#11]
Deben haber multiples formas de internacionalizar y sugiero los siguientes pasos, para que podamos decidir como hacerlo.

1. Ver la charla sobre [traducir R en UseR2021](https://www.conftool.org/user2021/index.php?page=browseSessions&form_session=84&presentations=show) para ver si algo aplica a paquetes.
2. Validar si el apquete [potools](https://cran.r-project.org/web/packages/potools/index.html) se mencionó en 1) o si es una alternativa a considerar.
3. Busqueda en internet para validar si no estamos pasando de alto alguna otra alternativa.

Como resultado deja por favor una propuesta de como hacer la traducción aqui abajo que podamos discutir.

**Comment by danielgranadoscampos** [comment]
### Internacionalización de Ixplorer

#### [Translating R to your language](https://www.youtube.com/watch?v=S3Qhqf9u6ao&t=54s)

R tiene soporte para traducciones desde cerca del 2005, al día de hoy se mantienen 16 idiomas.

Tanto el mensaje como las funciones que las producen son importantes en las traducciones. Las funciones principales reconocidas por R como funciones que producen mensajes traducibles son: `message(), stop() y warning()`

Todas trabajan mediante el sistema de gettext, que hace posibles las traducciones en R. Esto involucra el manejo de archivos como .po .pot y .mo

[Translating R to your language](https://www.youtube.com/watch?v=S3Qhqf9u6ao&t=54s) introduce al paquete [potools](https://github.com/MichaelChirico/potools) como una alternativa para sobreponerse a la complejidad del sistema gettext en la traducción de paquetes de R y su internacionalización.

#### [potools: Tools for Portability and Internationalization of R packages](https://github.com/MichaelChirico/potools)

Esencialmente está diseñado para disminuir el esfuerzo de traducir aquellas comunicaciones que los paquetes tienen con los usuarios (mensajes, advertencias, etc.). No solamente está centrado en construir las traducciones si no también en su mantenimiento.

La función principal en [potools](https://github.com/MichaelChirico/potools) es `translate_package()` que hace interactivo el proceso y que pretende ser la única parada en el proceso de traducción. Además, integra también herramientas de diagnostico para construir los mensajes en el paquete de tal manera que sean fácilmente traducibles.

#### Otras maneras de traducir...

Además de potools, existen otras herramientas que se centran en facilitar el manejo de archivos .po .pot y .mo para los desarrolladores.

[PoEdit](https://poedit.net), por ejemplo se utiliza en la internacionalización de apps y websites, de la misma manera lo hace [GNOME Translation Editor](https://wiki.gnome.org/Apps/Gtranslator) y [Pootle](https://pootle.translatehouse.org).

A pesar de que estas opciones son utilizadas también en la internacionalización de software, talvez ninguna esté diseñada con la especificidad que tiene [potools](https://github.com/MichaelChirico/potools) para el ambiente de R y los paquetes, por lo que considero que es la opción más viable. Por el diseño de [potools](https://github.com/MichaelChirico/potools), sería necesario que ixplorer se centre solamente en un idioma y de ahí en adelante usar[ potools ](https://github.com/MichaelChirico/potools)para ejecutar las traducciones necesarias.

##### Otra presentación de potools
[Michael Chirico | Making .pot-ery with R: Translations in R Packages | RStudio](https://www.youtube.com/watch?v=N-7LdfAZBeA)

**Comment by FvD** [comment]
@danielgranadoscampos toma uno o dos funciones como prueba de concepto. Como lenguaje base propongo que sea inglés, y la traducción con `potools` a español. Pero lo quisiera ver en acción para que podamos entender el impacto y hacer el plan para la traducción de todos los componentes.

**Comment by ronnyhdez** [comment]
Ya la desicion está tomada y en proceso de implementación.
