### ISSUE TITLE
Note for the current_tickets function documentation

### ISSUE THREAD

**Issue by andreavargasmon** [ixpantia/ixplorer#43]
You can only get the current tickets that have an assignee, otherwise, they will not appear here

**Comment by ronnyhdez** [comment]
This was part of the original design. To list tickets with an assignee. Otherwise, we consider the ticket to be without priority. This avoids having a long list on repos with a lot of open tickets without priority.

**Comment by andreavargasmontero** [comment]
@ronnyhdez yes and I think this is very well thought out. I just made the ticket to remember to include this caviet somewhere in the package or function's documentation
