### ISSUE TITLE
My tickets not showing up on "Team tickets"

### ISSUE THREAD

**Issue by andreavargasmon** [ixpantia/ixplorer#58]
I think we need to include all tickets in the "Team Tickets" tab because we need a place were all tikets from the repo are listed, currently we have:
my tickets in one lists
Everyonelse's tickets in another one

**Comment by ronnyhdez** [comment]
Team tickets use a filter to remove those that are assigned to the current user. The idea is to check just the tickets that are assassinated to all the team members
