### ISSUE TITLE
Cannot set a token in keyring

### ISSUE THREAD

**Issue by FvD** [ixpantia/ixplorer#70]
I have tried to go through the steps of setting up new authentication.

1. Fill out form "ixplorer authentication (see #71 for screenshot).
2. Set a password (not sure what to fill out here)
3. Set a keyring password.

After the last step it errors-out with the following comment.

````r
> ixplorer:::add_token()

Listening on http://127.0.0.1:3661
Warning in b_ss_keyring_create_direct(self, private, keyring, password) :
  Password ignored, will be read interactively
Warning: Error in key_set_with_value: could not find function "key_set_with_value"
  3: shiny::runApp
  2: runGadget
  1: ixplorer:::add_token
```

**Comment by danielgranadoscampos** [comment]
It seems there are missing "keyring::" in add_token (this will be fixed shortly).
Running library(keyring) for now should solve it 
Thank you!!

**Comment by FvD** [comment]
Solved
